### ISSUE TITLE
how to parametrize app?

### ISSUE THREAD

**Issue by supermihi** [eukaryote/pytest-tornasync#7]
Hi,
thank you for this great package!

Is there a way to parametrize the creation of the app, depending on the test? I might have something like 

```python
@pytest.fixture
def app(database):
    import yourapp
    return yourapp.make_app(database)  # a tornado.web.Application


def test_app_with_mock_db(http_server_client): # how to inject database here?
    resp = await http_server_client.fetch('/')
    assert resp.code == 200
```

**Comment by supermihi** [comment]
And a related question: is it possible to obtain a reference to `app` inside the test, to assert that, say, the API call has modified the backend in the expected way?

**Comment by eukaryote** [comment]
The 'app' is a standard pytest fixture that you define yourself, so you can add an 'app' parameter to your 'test_app_with_mock_db' test function in order to get a reference to the app. Likewise with the 'database' fixture. See https://docs.pytest.org/en/latest/fixture.html#fixtures-as-function-arguments for more info about how pytest fixture injection works.

**Comment by supermihi** [comment]
Thanks, that helps a lot! Apparently I did not yet fully understand how fixtures work. :)
